// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Data.Models;

public partial class Event
{
    public int EventId { get; set; }

    public string EventName { get; set; }

    public DateTime? EventDate { get; set; }

    public int? EventTypeId { get; set; }

    public string EventDescription { get; set; }

    public int? NumberTickets { get; set; }

    public string Sponsor { get; set; }

    public string SubjectCode { get; set; }

    public string Location { get; set; }

    public virtual EventType EventType { get; set; }

    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}