// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Data.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? RegistrationId { get; set; }

    public int? TicketId { get; set; }

    public int? TicketQuantity { get; set; }

    public DateTime? PaymentDate { get; set; }

    public decimal? AmountPaid { get; set; }

    public bool? Status { get; set; }

    public string PaymentType { get; set; }

    public virtual Registration Registration { get; set; }

    public virtual Ticket Ticket { get; set; }
}