// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Data.Models;

public partial class Registration
{
    public int RegistrationId { get; set; }

    public int? EventId { get; set; }

    public string VistorCode { get; set; }

    public string ParticipantName { get; set; }

    public string ParticipantType { get; set; }

    public string AttendeeEmail { get; set; }

    public DateOnly? RegistrationDate { get; set; }

    public string RegistrationPhone { get; set; }

    public decimal? FeePaid { get; set; }

    public bool? Checkin { get; set; }

    public DateTime? CheckinTime { get; set; }

    public int? CustomerId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Events Event { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}