// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Data.Models;

public partial class Ticket
{
    public int TicketId { get; set; }

    public int? EventId { get; set; }

    public string TicketType { get; set; }

    public decimal? Price { get; set; }

    public int? AvailableQuantity { get; set; }

    public virtual Events Event { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}