// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Event.Data.Models;

public partial class Ticket
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int TicketId { get; set; }

    public int? EventId { get; set; }

    public string TicketType { get; set; }

    public decimal? Price { get; set; }

    public int? AvailableQuantity { get; set; }
    public DateTime? StartedTime { get; set; }

    public DateTime? EndedTime { get; set; }

    public DateTime CreatedDate { get; set; }
    public string? CreatedBy { get; set; }
    public DateTime UpdatedDate { get; set; }
    public string? UpdatedBy { get; set; }
    public bool? Status { get; set; }

    public virtual Events Event { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}